"use client";
import {FormEvent,useMemo,useState} from "react";
type Msg={role:"agent"|"user";text:string};
type Pillar="attract"|"convert"|"operate"|"measure"|"scale";
type AgentState={nextQuestion:string;coverage:Record<Pillar,number>;evidence:{pillar:Pillar;evidence:string;confidence:number;source:"user"}[];ready:boolean;_provider?:"gemini"|"fallback"|"error";_reason?:string;_model?:string};
const pillarKeys:Pillar[]=["attract","convert","operate","measure","scale"];
const names:Record<Pillar,string>={attract:"Atrair",convert:"Converter",operate:"Operar",measure:"Medir",scale:"Escalar"};
const firstQuestion="Pra começar: me conta com tuas palavras o que a empresa faz, para quem vende, como ganha dinheiro hoje e qual é o principal desafio que tu gostaria de resolver.";
export default function MendesScan(){
 const [open,setOpen]=useState(false),[input,setInput]=useState(""),[history,setHistory]=useState<Msg[]>([{role:"agent",text:firstQuestion}]),[agent,setAgent]=useState<AgentState|null>(null),[loading,setLoading]=useState(false),[contact,setContact]=useState({name:"",company:"",whatsapp:"",email:""}),[captured,setCaptured]=useState(false),[submitting,setSubmitting]=useState(false);
 const userAnswers=useMemo(()=>history.filter(m=>m.role==="user").map(m=>m.text),[history]);
 const done=Boolean(agent?.ready);
 const scores=useMemo(()=>Object.fromEntries(pillarKeys.map(k=>[k,Math.round(agent?.coverage?.[k]??20)])) as Record<Pillar,number>,[agent]);
 const overall=Math.round(Object.values(scores).reduce((a,b)=>a+b,0)/5);const low=pillarKeys.slice().sort((a,b)=>scores[a]-scores[b])[0];
 async function send(e:FormEvent){e.preventDefault();const answer=input.trim();if(answer.length<8||loading)return;const nextHistory=[...history,{role:"user" as const,text:answer}];setHistory(nextHistory);setInput("");setLoading(true);try{const chronological=nextHistory.map(m=>m.text);const r=await fetch("/api/scan/agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({history:chronological})});if(!r.ok)throw new Error("agent");const data:AgentState=await r.json();setAgent(data);setHistory(h=>[...h,{role:"agent",text:data.nextQuestion}])}catch{setHistory(h=>[...h,{role:"agent",text:"Não consegui processar essa resposta agora. Pode tentar enviar novamente em alguns segundos?"}])}finally{setLoading(false)}}
 async function submitLead(e:FormEvent){e.preventDefault();if(!contact.name||!contact.whatsapp||submitting)return;setSubmitting(true);try{const answers=Object.fromEntries(userAnswers.map((v,i)=>[`resposta_${i+1}`,v]));const r=await fetch("/api/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contact,answers,scores,overall,evidence:agent?.evidence||[],conversation:history})});if(!r.ok)throw new Error("submit");setCaptured(true)}catch{alert("Não consegui salvar tua análise agora. Tenta novamente em instantes.")}finally{setSubmitting(false)}}
 return <><button className="primary scanStart" onClick={()=>setOpen(true)}>Quero minha pré-análise <b>↗</b></button>{open&&<div className="scanModal" role="dialog" aria-modal="true"><button className="scanClose" onClick={()=>setOpen(false)}>×</button><div className="scanPanel scanConversation"><div className="scanTop"><span>MENDES SCAN · ASSISTENTE VIRTUAL</span><b>{done?"ANÁLISE":"CONVERSA"}</b></div>
 {!done?<><div className="chatLog">{history.slice(-6).map((m,i)=><div className={"bubble "+m.role} key={i}>{m.role==="agent"&&<small>MENDES · IA</small>}<p>{m.text}</p></div>)}{loading&&<div className="bubble agent"><small>MENDES · IA</small><p>Analisando tua resposta...</p></div>}</div><form className="chatComposer" onSubmit={send}><textarea autoFocus value={input} onChange={e=>setInput(e.target.value)} placeholder="Pode responder do teu jeito..." rows={4}/><div><span>{userAnswers.length} respostas · conversa adaptativa{agent?._provider ? ` · ${agent._provider}${agent._reason ? ` (${agent._reason})` : ""}` : ""}</span><button disabled={input.trim().length<8||loading}>{loading?"Analisando...":"Enviar"} <b>↗</b></button></div></form></>:
 !captured?<div className="leadGate"><small>LEITURA PRONTA</small><h3>Já tenho contexto suficiente para montar tua pré-análise.</h3><p>Antes de liberar o resultado, deixa teus dados para eu identificar essa conversa e o Studio conseguir continuar contigo caso faça sentido.</p><form onSubmit={submitLead}><input placeholder="Teu nome *" value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/><input placeholder="Empresa" value={contact.company} onChange={e=>setContact({...contact,company:e.target.value})}/><input placeholder="WhatsApp *" value={contact.whatsapp} onChange={e=>setContact({...contact,whatsapp:e.target.value})}/><input type="email" placeholder="E-mail" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/><button className="primary" disabled={submitting}>{submitting?"Salvando análise...":"Ver minha pré-análise"} <b>↗</b></button></form><span className="privacy">Usamos esses dados somente para identificar tua análise e dar continuidade ao contato.</span></div>:
 <div className="scanResult"><small>PRÉ-ANÁLISE · {contact.company||contact.name}</small><div className="scoreBig">{overall}<span>/100</span></div><h3>O primeiro eixo que merece investigação é <em>{names[low]}</em>.</h3><div className="scoreBars">{pillarKeys.map(k=><div key={k}><label>{names[k]} <b>{scores[k]}</b></label><i><span style={{width:`${scores[k]}%`}}/></i></div>)}</div><p>Essa leitura é preliminar e foi construída a partir da conversa. No Scan completo, o Studio valida números, evidências e prioridades antes de recomendar qualquer solução.</p><div className="scanResultActions"><a className="primary" href={`https://wa.me/5551984705191?text=${encodeURIComponent(`Oi, sou ${contact.name} da ${contact.company||"minha empresa"}. Fiz a pré-análise do Mendes Scan e quero agendar o Scan completo.`)}`} target="_blank" rel="noreferrer">Agendar Scan completo <b>↗</b></a></div></div>}
 </div></div>}</>
}